project:
  type: website

website:
  title: "Quinn Asena"
  description: "Personal research website of Quinn Asena — ecologist and data scientist studying ecological dynamics, palaeoecology, and resilience."
  favicon: favicon.ico
  google-analytics: "G-HT71J1MK87"
  navbar:
    toggle-position: right
    background: "#374699"
    foreground: "#FFFFFF"
    search: true
    left:
      - href: my-research.qmd
        text: Research
      - href: talks.qmd
        text: Talks
      - href: resources-posts/resources-custom-listing.qmd
        text: Resources
      - href: about.qmd
        text: About
      - href: https://quinnasena.github.io/CV/resume_refs.html
        text: CV
    right:
      - icon: envelope
        href: mailto:asenaq@caryinstitute.org
      - icon: github
        href: https://github.com/QuinnAsena
      - icon: linkedin
        href: https://www.linkedin.com/in/quinn-asena-a394202a4/
      - icon: fingerprint
        menu:
          - text: Cary Institute of Ecosystem Studies
            href: https://www.caryinstitute.org/science/research-support/quinn-asena
          - text: Forest Futures lab
            href: https://forestfutureslab.org/
          - text: Ives Lab
            href: https://ives.labs.wisc.edu/people/
          - text: Williams Lab
            href: https://williamspaleolab.github.io/people/
          - text: Perry Lab
            href: https://spatialecol.com/
  page-footer:
    left: "© 2026 Quinn Asena"
    center: "Built with [Quarto](https://quarto.org/)"
    right:
      - icon: envelope
        href: mailto:asenaq@caryinstitute.org
      - icon: github
        href: https://github.com/QuinnAsena
      - icon: linkedin
        href: https://www.linkedin.com/in/quinn-asena-a394202a4/

format:
  html:
    theme:
      - lux
      - styles.scss
    toc: true
    link-external-newwindow: true


