project:
  type: website

website:
  title: "Quinn Asena"
  navbar:
    toggle-position: right
    background: "#374699"
    foreground: "#FFFFFF"
    favicon: emoji-smile-fill
    search: false
    right:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About me
      - href: my-research.qmd
        text: My research
      - href: resources.qmd
        text: Packages and resources
      - href: talks.qmd
        text: Talks
      - href: https://quinnasena.github.io/CV/resume_refs.html
        text: CV
    tools:
#      - icon: mortarboard-fill
#        href: https://quinnasena.github.io/CV/resume_refs.html
      - icon: envelope
        href: mailto:qasena@wisc.edu
      - icon: github
        href: https://github.com/QuinnAsena
      - icon: fingerprint
        menu:
          - text: Ives Lab
            href: https://ives.labs.wisc.edu/people/
          - text: Williams Lab
            href: https://williamspaleolab.github.io/people/
          - text: Perry Lab
            href: https://spatialecol.com/

format:
  html:
    theme: lux
    css: styles.css
    toc: true



